/* Plugin generated by AMXX-Studio */

#include <amxmodx>

#define PLUGIN "Aliasy weaponmod"
#define VERSION "0.1"
#define AUTHOR "ToRRent"


public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR)
	
	register_clcmd("an94", "Kup_AN")
}

public Kup_AN(id)
	client_cmd(id, "wpnbuy 0")
	
