/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <codmod>
#include <cstrike>

new const perk_name[] = "Przysposobienie obronne";
new const perk_desc[] = "Dostajesz 200 pancerza";


public plugin_init() 
{
	register_plugin(perk_name, "1.0", "QTM_Peyote");
	
	cod_register_perk(perk_name, perk_desc);
}
public cod_perk_enabled(id)
	cs_set_user_armor(id, 200, CS_ARMOR_VESTHELM);

public cod_perk_disabled(id)
	cs_set_user_armor(id, 0, CS_ARMOR_NONE);
