/* Plugin generated by AMXX-Studio */

#include <amxmodx>

#define PLUGIN "Info"
#define VERSION "0.1"
#define AUTHOR "ToRRent"


public plugin_init() {
	register_plugin(PLUGIN, VERSION, AUTHOR)
	
	register_event("HLTV", "NowaRunda",  "a", "1=0", "2=0");
}

public NowaRunda()
{
	client_print(0, print_center, "Na mapie de_rats_kitchoon_v2 gramy bez obrazen za upadek !");
}